// Generated by script/generate-emoji-modifiers.
// You MUST commit any modifications to this file.

const supported = new Set<string>([])

export function isModifiable(emoji: string): boolean {
  return supported.has(emoji)
}
